version: 0.0
os: linux
files:
  - source: /
    destination: /home/devoj/BotDiscord  # Caminho onde o c칩digo ser치 implantado
hooks:
  AfterInstall:
    - location: scripts/start_bot.sh
      timeout: 300
      runas: devoj  # Usu치rio que executar치 o script
